// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: pb/user/v1/user_event.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on UserEvent with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UserEvent) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserEvent with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UserEventMultiError, or nil
// if none found.
func (m *UserEvent) ValidateAll() error {
	return m.validate(true)
}

func (m *UserEvent) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for UserId

	// no validation rules for OperationType

	if m.BeforeChange != nil {

		if all {
			switch v := interface{}(m.GetBeforeChange()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, UserEventValidationError{
						field:  "BeforeChange",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, UserEventValidationError{
						field:  "BeforeChange",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetBeforeChange()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return UserEventValidationError{
					field:  "BeforeChange",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if m.AfterChange != nil {

		if all {
			switch v := interface{}(m.GetAfterChange()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, UserEventValidationError{
						field:  "AfterChange",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, UserEventValidationError{
						field:  "AfterChange",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetAfterChange()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return UserEventValidationError{
					field:  "AfterChange",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return UserEventMultiError(errors)
	}

	return nil
}

// UserEventMultiError is an error wrapping multiple validation errors returned
// by UserEvent.ValidateAll() if the designated constraints aren't met.
type UserEventMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserEventMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserEventMultiError) AllErrors() []error { return m }

// UserEventValidationError is the validation error returned by
// UserEvent.Validate if the designated constraints aren't met.
type UserEventValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserEventValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserEventValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserEventValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserEventValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserEventValidationError) ErrorName() string { return "UserEventValidationError" }

// Error satisfies the builtin error interface
func (e UserEventValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserEvent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserEventValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserEventValidationError{}
